name: "Milestone Notes"
description: "Create an .md file with closed issues based on a milestone number or regexp matching its title."
inputs:
  milestone-number:
    description: "Milestone number. Either this or match-milestone must be provided. Has precedence if both are."
    required: false
    default: "-"
  match-milestone:
    description: "Regular expression to match milestone title. Either this or milestone-number must be provided."
    required: false
    default: "-"
  repository:
    description: "username/repository to get milestone and issues for. Must be public."
    required: true
  labels:
    description: "Comma-separated labels of issues to include in the release notes"
    required: false
    default: "enhancement, bug"
  ignore:
    description: "Comma-separated labels of issues to exclude from the release notes"
    required: false
    default: "invalid, wontfix"
  filename:
    description: "Name of the file to write milestone notes to"
    required: false
    default: "milestone-notes.md"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.milestone-number }}
    - ${{ inputs.match-milestone }}
    - ${{ inputs.repository }}
    - ${{ inputs.labels }}
    - ${{ inputs.ignore }}
    - ${{ inputs.filename }}
branding:
  color: blue
  icon: list
