on:
  pull_request:
    branches: [master]
jobs:
  test-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate test release notes
        uses: ./
        with:
          match-milestone: "^1$"
          repository: ${{ github.repository }}
      - name: Show release notes
        run: cat milestone-notes.md
