on: [push]
#  pull_request:
#    branches: [master]
jobs:
  test-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Generate test release notes
        uses: ./
        with:
          version-number: "1"
          repository: ${{ github.repository }}
      - name: Show release notes
        run: cat milestone-notes.md
